// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFiJRCuxuLjd5xWeOqKfHQFsPuIq2ot0w',
    appId: '1:91662202252:web:6910ac985227b40a3152a9',
    messagingSenderId: '91662202252',
    projectId: 'seat-and-set',
    authDomain: 'seat-and-set.firebaseapp.com',
    storageBucket: 'seat-and-set.firebasestorage.app',
    measurementId: 'G-BPTDPCM61K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcCyQcCCmRDk9yr5PbBU2kqcp8KFJ9hHs',
    appId: '1:91662202252:android:6d9bdde9dd2a67403152a9',
    messagingSenderId: '91662202252',
    projectId: 'seat-and-set',
    storageBucket: 'seat-and-set.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMg7Kls1T5OtxXsniv3UW-SHoMdvKN7lQ',
    appId: '1:91662202252:ios:da0421365fd443283152a9',
    messagingSenderId: '91662202252',
    projectId: 'seat-and-set',
    storageBucket: 'seat-and-set.firebasestorage.app',
    iosBundleId: 'com.example.seatAndSet',
  );
}
